language: go
go:
- 1.13.3
sudo: false
before_install:
- go get github.com/mitchellh/gox
- go get -v ./...
script:
- gox -osarch="linux/arm" -osarch="linux/amd64" -osarch="darwin/amd64" .
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: iWq1izLEvcTuXkwR+earpS4sDecXW7datNNdBVCmCysaZ2Y3MkwFsEDCQqSImFDsJ4DDaE56m5Fs8GeM4AOFwg6W8mPuxoLQvMHgofXyVJbRt4Kg18l2ITL54KVARQC1UfYf6KTZzmT3OxHi3/TZEAUas5xj8zaTdEcX01tkb4pZvnbi2n/aU2qY3tnJJg3xv6XBZnSD+897zGmz8tt6Qltux6jKfCcYnp9hdtoWPDCwM4Hr+JTV+3XTBp8aq2HWNr60h0VsUinNOvT9F1wZsYQT3+Mta1Elwq3Z6fX0rMZ/VquJefp6fO0VE4pR/0uBMxZpAW3VAYMPC/jj3BPQ9RT4A+6Hpw5Y+4M/RSoIgMjXE6LnoqpuegjBOEcmH5BjUD2UIsTeMByLcWlu1osHokkl52Qnz5QyBvFftCn04LMSy3oP7BpFAFLsHTwOXmVYyk4A+K5ewxlqtg3JsW+UAqJ3WlzSymkafI+oCMvNlDeusYEGkrDztSU3NU5tpG2mw2zRF6iacDCcI1mpNVKhkAdFM2XhQTskrHldj8CS6lhAt0UXHxas5A9qnIsB1IE3Cmi42skrNqVNrjN7NC2GDGlplmINEDiPw3CYM7K/F7VwkIQV/0lQM8azE4py/IwBV/1HY+t94L+uaaoZi/V5ORpJLW+vHQu5qAcOvQzpduQ=
  file:
    - traffic-simulator_linux_amd64
    - traffic-simulator_linux_arm
    - traffic-simulator_darwin_amd64
  on:
    tags: true
